version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:13.3.6-ce.0'
    restart: always
    hostname: gitlab-ce
    privileged: true
    container_name: gitlab-ce
    ports:
      - "10022:22"
      - "10080:80"
      - "10443:443"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./conf:/etc/gitlab:Z
      - ./data:/var/opt/gitlab:Z
      - ./logs:/var/log/gitlab:Z
