version: '3'

services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner'
    restart: always
    hostname: gitlab-runner
    privileged: true
    container_name: gitlab-runner
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./config:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
