version: '3'

services:
  mysql:
    image: 'mysql'
    restart: always
    hostname: eyeBlueTank_mysql
    privileged: true
    container_name: eyeBlueTank_mysql
    ports:
      - "23306:3306"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./mysql/db:/var/lib/mysql:Z
      - ./mysql/init:/docker-entrypoint-initdb.d:Z
      - ./mysql/conf/my.cnf:/etc/my.cnf:Z
    networks:
      - eyeBlueTank
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  tank:
    image: 'eyeblue/tank:3.1.0'
    restart: always
    hostname: eyeBlueTank_tank
    privileged: true
    container_name: eyeBlueTank_tank
    ports:
      - "16010:6010"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    volumes:
      - ./tank/data:/data/build/matter:Z
    depends_on:
      - mysql
    networks:
      - eyeBlueTank

networks:
  eyeBlueTank: